### ISSUE TITLE
替所有活動加上影片連結、共筆連結

### ISSUE THREAD

**Issue by zbryikt** [g0v/jothon-net#8]
黑客松活動檔位於 https://github.com/g0v/jothon-net/tree/master/data/events/
需要加上共筆連結與影片連結. 影片需區分提案、短講與成果報告

**Comment by SeanGau** [comment]
已完成
於各活動的yaml內添加
video_pitch: https://www.youtube.com/watch?v=
video_talk: https://www.youtube.com/watch?v=
video_demo: https://www.youtube.com/watch?v=
